<?php

/**
 * @file
 * Workbench module file.
 */

use Drupal\workbench\Workbench;
use Drupal\workbench\WorkbenchInterface;

/**
 * Implements hook_permission().
 */
function workbench_permission() {
  $permissions = array(
    'access workbench' => array(
      'title' => t('Access My Workbench page'),
    ),
  );
  return $permissions;
}

/**
 * Implements hook_toolbar().
 */
function workbench_toolbar() {
  $user = \Drupal::currentUser();

  $items = array();
  if ($user->hasPermission('access workbench')) {
    $links = workbench_renderable_links();
    $shortcut_set = shortcut_current_displayed_set();
    $configure_link = NULL;
    if (!empty($links) || !empty($configure_link)) {
      $items['workbench'] = array(
        '#type' => 'toolbar_item',
        'tab' => array(
          '#type' => 'link',
          '#title' => t('Workbench'),
          '#href' => 'admin/workbench`',
          '#attributes' => array(
            'title' => t('Workbench'),
            'class' => array('toolbar-icon', 'toolbar-icon-shortcut'),
          ),
        ),
        'tray' => array(
          '#heading' => t('My Workbench'),
          'shortcuts' => $links,
          'configure' => $configure_link,
        ),
        '#weight' => -15,
        '#attached' => array(
          'library' => array(
            'shortcut/drupal.shortcut',
          ),
        ),
      );
    }
  }
  return $items;
}

/**
 * Gets the links to use for Workbench.
 */
function workbench_renderable_links() {
  $workbench_links = array();
  $workbench = new Workbench();
  $links = $workbench->getLinks();

  if (!empty($links)) {
    $workbench_links = array(
      '#theme' => 'links__toolbar_workbench',
      '#links' => $links,
      '#attributes' => array(
        'class' => array('menu'),
      ),
      // @TODO: cache per role.
      '#cache' => array(
        'tags' => 'workbench',
      ),
    );
  }
  return $workbench_links;
}

/**
 * Implements hook_workbench_links().
 */
function workbench_workbench_links() {
  $links[] = array(
    'title' => 'My Workbench',
    'route_name' => 'workbench.overview',
  );
  return $links;
}
